
package com.libf.ws.wsdemon1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSDemon1Service", targetNamespace = "http://webservice.libf.com/", wsdlLocation = "http://localhost:8080/services?wsdl")
public class WSDemon1Service
    extends Service
{

    private final static URL WSDEMON1SERVICE_WSDL_LOCATION;
    private final static WebServiceException WSDEMON1SERVICE_EXCEPTION;
    private final static QName WSDEMON1SERVICE_QNAME = new QName("http://webservice.libf.com/", "WSDemon1Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/services?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSDEMON1SERVICE_WSDL_LOCATION = url;
        WSDEMON1SERVICE_EXCEPTION = e;
    }

    public WSDemon1Service() {
        super(__getWsdlLocation(), WSDEMON1SERVICE_QNAME);
    }

    public WSDemon1Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSDEMON1SERVICE_QNAME, features);
    }

    public WSDemon1Service(URL wsdlLocation) {
        super(wsdlLocation, WSDEMON1SERVICE_QNAME);
    }

    public WSDemon1Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSDEMON1SERVICE_QNAME, features);
    }

    public WSDemon1Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSDemon1Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSDemon1
     */
    @WebEndpoint(name = "WSDemon1Port")
    public WSDemon1 getWSDemon1Port() {
        return super.getPort(new QName("http://webservice.libf.com/", "WSDemon1Port"), WSDemon1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSDemon1
     */
    @WebEndpoint(name = "WSDemon1Port")
    public WSDemon1 getWSDemon1Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.libf.com/", "WSDemon1Port"), WSDemon1.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSDEMON1SERVICE_EXCEPTION!= null) {
            throw WSDEMON1SERVICE_EXCEPTION;
        }
        return WSDEMON1SERVICE_WSDL_LOCATION;
    }

}
