
package com.libf.ws.stockInfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StockInfoWSSoap", targetNamespace = "http://webxml.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StockInfoWSSoap {


    /**
     * <br /><h3>获得支持使用分格符 | 的多个中国股票及时行情数据</h3><p>输入参数：theStockCode = 股票代号，UserID：商业用户ID，返回数据：一个一维字符串数组的及时行情数据 <a href="stockinfows_read_me.txt" target="_blank">详细说明</a></p><br />
     * 
     * @param theStockCode
     * @param userID
     * @return
     *     returns com.libf.ws.stockInfo.ArrayOfString
     */
    @WebMethod(action = "http://webxml.com.cn/getStockInfo")
    @WebResult(name = "getStockInfoResult", targetNamespace = "http://webxml.com.cn/")
    @RequestWrapper(localName = "getStockInfo", targetNamespace = "http://webxml.com.cn/", className = "com.libf.ws.stockInfo.GetStockInfo")
    @ResponseWrapper(localName = "getStockInfoResponse", targetNamespace = "http://webxml.com.cn/", className = "com.libf.ws.stockInfo.GetStockInfoResponse")
    public ArrayOfString getStockInfo(
        @WebParam(name = "theStockCode", targetNamespace = "http://webxml.com.cn/")
        String theStockCode,
        @WebParam(name = "userID", targetNamespace = "http://webxml.com.cn/")
        String userID);

}
