
package com.libf.ws.stockInfo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * <a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> <strong>中国股票及时行情数据 WEB 服务（2）（支持香港、深圳和上海股市的全部基金、债券和股票）</strong>，数据即时更新。此中国股票行情数据 WEB 服务仅作为用户获取信息之目的，并不构成投资建议。<a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> 和/或其各供应商不为本页面提供信息的错误、残缺、延迟或因依靠此信息所采取的任何行动负责。<strong>市场有风险，投资需谨慎</strong>。<br /><strong>此中国股票行情数据只提供给商业用户使用</strong>，若有需要请<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">联系我们</a>，欢迎技术交流。 QQ：8409035<br /><strong>使用本站 WEB 服务请注明或链接本站：http://www.webxml.com.cn/ 感谢大家的支持</strong>！<br /><br /><span style="color:#D20000;"><strong>股票输入注意事项</strong>：因上海股票和深圳股票在代号上有重叠，所以在输入上海股票请在代号前加 SH，深圳加 SZ，香港加 HK（不区分大小写），例：上证指数 sh000001，深发展A sz000001，长江实业 hk00001。如不输入股票代号默认上证指数 sh000001。<strong>支持使用 | 符号分割的多股票查询</strong></span><br /><br />&nbsp;
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StockInfoWS", targetNamespace = "http://webxml.com.cn/", wsdlLocation = "http://www.webxml.com.cn/WebServices/StockInfoWS.asmx?wsdl")
public class StockInfoWS
    extends Service
{

    private final static URL STOCKINFOWS_WSDL_LOCATION;
    private final static WebServiceException STOCKINFOWS_EXCEPTION;
    private final static QName STOCKINFOWS_QNAME = new QName("http://webxml.com.cn/", "StockInfoWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.webxml.com.cn/WebServices/StockInfoWS.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STOCKINFOWS_WSDL_LOCATION = url;
        STOCKINFOWS_EXCEPTION = e;
    }

    public StockInfoWS() {
        super(__getWsdlLocation(), STOCKINFOWS_QNAME);
    }

    public StockInfoWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), STOCKINFOWS_QNAME, features);
    }

    public StockInfoWS(URL wsdlLocation) {
        super(wsdlLocation, STOCKINFOWS_QNAME);
    }

    public StockInfoWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STOCKINFOWS_QNAME, features);
    }

    public StockInfoWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StockInfoWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StockInfoWSSoap
     */
    @WebEndpoint(name = "StockInfoWSSoap")
    public StockInfoWSSoap getStockInfoWSSoap() {
        return super.getPort(new QName("http://webxml.com.cn/", "StockInfoWSSoap"), StockInfoWSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockInfoWSSoap
     */
    @WebEndpoint(name = "StockInfoWSSoap")
    public StockInfoWSSoap getStockInfoWSSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://webxml.com.cn/", "StockInfoWSSoap"), StockInfoWSSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns StockInfoWSSoap
     */
    @WebEndpoint(name = "StockInfoWSSoap12")
    public StockInfoWSSoap getStockInfoWSSoap12() {
        return super.getPort(new QName("http://webxml.com.cn/", "StockInfoWSSoap12"), StockInfoWSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockInfoWSSoap
     */
    @WebEndpoint(name = "StockInfoWSSoap12")
    public StockInfoWSSoap getStockInfoWSSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://webxml.com.cn/", "StockInfoWSSoap12"), StockInfoWSSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns StockInfoWSHttpGet
     */
    @WebEndpoint(name = "StockInfoWSHttpGet")
    public StockInfoWSHttpGet getStockInfoWSHttpGet() {
        return super.getPort(new QName("http://webxml.com.cn/", "StockInfoWSHttpGet"), StockInfoWSHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockInfoWSHttpGet
     */
    @WebEndpoint(name = "StockInfoWSHttpGet")
    public StockInfoWSHttpGet getStockInfoWSHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://webxml.com.cn/", "StockInfoWSHttpGet"), StockInfoWSHttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns StockInfoWSHttpPost
     */
    @WebEndpoint(name = "StockInfoWSHttpPost")
    public StockInfoWSHttpPost getStockInfoWSHttpPost() {
        return super.getPort(new QName("http://webxml.com.cn/", "StockInfoWSHttpPost"), StockInfoWSHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockInfoWSHttpPost
     */
    @WebEndpoint(name = "StockInfoWSHttpPost")
    public StockInfoWSHttpPost getStockInfoWSHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://webxml.com.cn/", "StockInfoWSHttpPost"), StockInfoWSHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STOCKINFOWS_EXCEPTION!= null) {
            throw STOCKINFOWS_EXCEPTION;
        }
        return STOCKINFOWS_WSDL_LOCATION;
    }

}
