
package com.libf.ws.compiling;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceDemonService", targetNamespace = "http://webservice.libf.com/", wsdlLocation = "http://localhost:9001/Service/WebServiceDemon?wsdl")
public class WebServiceDemonService
    extends Service
{

    private final static URL WEBSERVICEDEMONSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEDEMONSERVICE_EXCEPTION;
    private final static QName WEBSERVICEDEMONSERVICE_QNAME = new QName("http://webservice.libf.com/", "WebServiceDemonService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9001/Service/WebServiceDemon?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEDEMONSERVICE_WSDL_LOCATION = url;
        WEBSERVICEDEMONSERVICE_EXCEPTION = e;
    }

    public WebServiceDemonService() {
        super(__getWsdlLocation(), WEBSERVICEDEMONSERVICE_QNAME);
    }

    public WebServiceDemonService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEDEMONSERVICE_QNAME, features);
    }

    public WebServiceDemonService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEDEMONSERVICE_QNAME);
    }

    public WebServiceDemonService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEDEMONSERVICE_QNAME, features);
    }

    public WebServiceDemonService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceDemonService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceDemon
     */
    @WebEndpoint(name = "WebServiceDemonPort")
    public WebServiceDemon getWebServiceDemonPort() {
        return super.getPort(new QName("http://webservice.libf.com/", "WebServiceDemonPort"), WebServiceDemon.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceDemon
     */
    @WebEndpoint(name = "WebServiceDemonPort")
    public WebServiceDemon getWebServiceDemonPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.libf.com/", "WebServiceDemonPort"), WebServiceDemon.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEDEMONSERVICE_EXCEPTION!= null) {
            throw WEBSERVICEDEMONSERVICE_EXCEPTION;
        }
        return WEBSERVICEDEMONSERVICE_WSDL_LOCATION;
    }

}
