
package com.libf.ws.compiling;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceDemon", targetNamespace = "http://webservice.libf.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceDemon {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "myAction")
    @WebResult(name = "thisResult", targetNamespace = "")
    @RequestWrapper(localName = "transWords", targetNamespace = "http://webservice.libf.com/", className = "com.libf.ws.compiling.TransWords")
    @ResponseWrapper(localName = "transWordsResponse", targetNamespace = "http://webservice.libf.com/", className = "com.libf.ws.compiling.TransWordsResponse")
    @Action(input = "myAction", output = "http://webservice.libf.com/WebServiceDemon/transWordsResponse")
    String transWords(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
