
package com.libf.ws.bond;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * <a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> <strong>中国股票行情分时走势预览缩略图 WEB 服务（支持深圳和上海股市的全部基金、债券和股票）</strong>，数据即时更新。此中国股票走势预览缩略图 WEB 服务仅作为用户获取信息之目的，并不构成投资建议。<a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> 和/或其各供应商不为本页面提供信息的错误、残缺、延迟或因依靠此信息所采取的任何行动负责。<strong>市场有风险，投资需谨慎</strong>。<br />此中国股票行情数据Web Services请不要用于任何商业目的，若有需要请<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">联系我们</a>，欢迎技术交流。 QQ：8409035<br /><strong>使用本站 WEB 服务请注明或链接本站：http://www.webxml.com.cn/ 感谢大家的支持</strong>！<br /><br /><span style="color:#D20000;"><strong>股票输入注意事项</strong>：因上海股票和深圳股票在代号上有重叠，所以在输入上海股票请在代号前加 SH，深圳加 SZ（不区分大小写），例：上证指数 sh000001，深发展A sz000001。如不输入股票代号默认上证指数 sh000001</span><br /><br />&nbsp;
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ChinaStockSmallImageWS", targetNamespace = "http://WebXml.com.cn/", wsdlLocation = "http://www.webxml.com.cn/webservices/ChinaStockSmallImageWS.asmx?wsdl")
public class ChinaStockSmallImageWS
    extends Service
{

    private final static URL CHINASTOCKSMALLIMAGEWS_WSDL_LOCATION;
    private final static WebServiceException CHINASTOCKSMALLIMAGEWS_EXCEPTION;
    private final static QName CHINASTOCKSMALLIMAGEWS_QNAME = new QName("http://WebXml.com.cn/", "ChinaStockSmallImageWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.webxml.com.cn/webservices/ChinaStockSmallImageWS.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHINASTOCKSMALLIMAGEWS_WSDL_LOCATION = url;
        CHINASTOCKSMALLIMAGEWS_EXCEPTION = e;
    }

    public ChinaStockSmallImageWS() {
        super(__getWsdlLocation(), CHINASTOCKSMALLIMAGEWS_QNAME);
    }

    public ChinaStockSmallImageWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHINASTOCKSMALLIMAGEWS_QNAME, features);
    }

    public ChinaStockSmallImageWS(URL wsdlLocation) {
        super(wsdlLocation, CHINASTOCKSMALLIMAGEWS_QNAME);
    }

    public ChinaStockSmallImageWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHINASTOCKSMALLIMAGEWS_QNAME, features);
    }

    public ChinaStockSmallImageWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChinaStockSmallImageWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ChinaStockSmallImageWSSoap
     */
    @WebEndpoint(name = "ChinaStockSmallImageWSSoap")
    public ChinaStockSmallImageWSSoap getChinaStockSmallImageWSSoap() {
        return super.getPort(new QName("http://WebXml.com.cn/", "ChinaStockSmallImageWSSoap"), ChinaStockSmallImageWSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChinaStockSmallImageWSSoap
     */
    @WebEndpoint(name = "ChinaStockSmallImageWSSoap")
    public ChinaStockSmallImageWSSoap getChinaStockSmallImageWSSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "ChinaStockSmallImageWSSoap"), ChinaStockSmallImageWSSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns ChinaStockSmallImageWSSoap
     */
    @WebEndpoint(name = "ChinaStockSmallImageWSSoap12")
    public ChinaStockSmallImageWSSoap getChinaStockSmallImageWSSoap12() {
        return super.getPort(new QName("http://WebXml.com.cn/", "ChinaStockSmallImageWSSoap12"), ChinaStockSmallImageWSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChinaStockSmallImageWSSoap
     */
    @WebEndpoint(name = "ChinaStockSmallImageWSSoap12")
    public ChinaStockSmallImageWSSoap getChinaStockSmallImageWSSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "ChinaStockSmallImageWSSoap12"), ChinaStockSmallImageWSSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns ChinaStockSmallImageWSHttpGet
     */
    @WebEndpoint(name = "ChinaStockSmallImageWSHttpGet")
    public ChinaStockSmallImageWSHttpGet getChinaStockSmallImageWSHttpGet() {
        return super.getPort(new QName("http://WebXml.com.cn/", "ChinaStockSmallImageWSHttpGet"), ChinaStockSmallImageWSHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChinaStockSmallImageWSHttpGet
     */
    @WebEndpoint(name = "ChinaStockSmallImageWSHttpGet")
    public ChinaStockSmallImageWSHttpGet getChinaStockSmallImageWSHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "ChinaStockSmallImageWSHttpGet"), ChinaStockSmallImageWSHttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns ChinaStockSmallImageWSHttpPost
     */
    @WebEndpoint(name = "ChinaStockSmallImageWSHttpPost")
    public ChinaStockSmallImageWSHttpPost getChinaStockSmallImageWSHttpPost() {
        return super.getPort(new QName("http://WebXml.com.cn/", "ChinaStockSmallImageWSHttpPost"), ChinaStockSmallImageWSHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChinaStockSmallImageWSHttpPost
     */
    @WebEndpoint(name = "ChinaStockSmallImageWSHttpPost")
    public ChinaStockSmallImageWSHttpPost getChinaStockSmallImageWSHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "ChinaStockSmallImageWSHttpPost"), ChinaStockSmallImageWSHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHINASTOCKSMALLIMAGEWS_EXCEPTION!= null) {
            throw CHINASTOCKSMALLIMAGEWS_EXCEPTION;
        }
        return CHINASTOCKSMALLIMAGEWS_WSDL_LOCATION;
    }

}
