
package com.libf.ws.bond;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ChinaStockSmallImageWSHttpGet", targetNamespace = "http://WebXml.com.cn/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ChinaStockSmallImageWSHttpGet {


    /**
     * <br /><h3>直接获得中国股票GIF走势预览缩略图</h3><p>输入参数：theStockCode 股票代号 String，如：sh000001，theImageType 预览图类型 Byte（必须）：theImageType = 1（小图） 返回数据：股票GIF分时走势预览缩略图。</p><br />
     * 
     * @param theStockCode
     * @param theImageType
     */
    @WebMethod
    public void getSmallImage(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "theStockCode")
        String theStockCode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "theImageType")
        String theImageType);

    /**
     * <br /><h3>直接获得中国股票GIF走势预览缩略图字节数组 </h3><p>输入参数：theStockCode 股票代号 String，如：sh000001，theImageType 预览图类型 Byte（必须）：theImageType = 1（小图）； 返回数据：股票GIF分时走势预览缩略图字节数组。</p><br />
     * 
     * @param theStockCode
     * @param theImageType
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(name = "base64Binary", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    public byte[] getSmallImageByte(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "theStockCode")
        String theStockCode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "theImageType")
        String theImageType);

}
