
package com.libf.ws.bond;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ChinaStockSmallImageWSSoap", targetNamespace = "http://WebXml.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ChinaStockSmallImageWSSoap {


    /**
     * <br /><h3>直接获得中国股票GIF走势预览缩略图</h3><p>输入参数：theStockCode 股票代号 String，如：sh000001，theImageType 预览图类型 Byte（必须）：theImageType = 1（小图） 返回数据：股票GIF分时走势预览缩略图。</p><br />
     * 
     * @param theStockCode
     * @param theImageType
     */
    @WebMethod(action = "http://WebXml.com.cn/getSmallImage")
    @RequestWrapper(localName = "getSmallImage", targetNamespace = "http://WebXml.com.cn/", className = "com.libf.ws.bond.GetSmallImage")
    @ResponseWrapper(localName = "getSmallImageResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.libf.ws.bond.GetSmallImageResponse")
    public void getSmallImage(
        @WebParam(name = "theStockCode", targetNamespace = "http://WebXml.com.cn/")
        String theStockCode,
        @WebParam(name = "theImageType", targetNamespace = "http://WebXml.com.cn/")
        short theImageType);

    /**
     * <br /><h3>直接获得中国股票GIF走势预览缩略图字节数组 </h3><p>输入参数：theStockCode 股票代号 String，如：sh000001，theImageType 预览图类型 Byte（必须）：theImageType = 1（小图）； 返回数据：股票GIF分时走势预览缩略图字节数组。</p><br />
     * 
     * @param theStockCode
     * @param theImageType
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "http://WebXml.com.cn/getSmallImageByte")
    @WebResult(name = "getSmallImageByteResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getSmallImageByte", targetNamespace = "http://WebXml.com.cn/", className = "com.libf.ws.bond.GetSmallImageByte")
    @ResponseWrapper(localName = "getSmallImageByteResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.libf.ws.bond.GetSmallImageByteResponse")
    public byte[] getSmallImageByte(
        @WebParam(name = "theStockCode", targetNamespace = "http://WebXml.com.cn/")
        String theStockCode,
        @WebParam(name = "theImageType", targetNamespace = "http://WebXml.com.cn/")
        short theImageType);

}
