
package com.libf.ws.email;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ValidateEmailWebServiceSoap", targetNamespace = "http://WebXml.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ValidateEmailWebServiceSoap {


    /**
     * <br /><h3>验证 Email 地址是否正确</h3><p>输入参数：EmailAddress = Email 地址（默认SMTP端口25），返回数据： Byte 字节。返回值： 0 = 请重新验证；1 = 邮件地址合法；2 = 只是域名正确；3 = 一个未知错误；4 = 邮件服务器没有找到；5 = 电子邮件地址错误；6 = 免费用户验证超过数量（50次/24小时）；7 = 商业用户不能通过验证</p><br />
     * 
     * @param theEmail
     * @return
     *     returns short
     */
    @WebMethod(operationName = "ValidateEmailAddress", action = "http://WebXml.com.cn/ValidateEmailAddress")
    @WebResult(name = "ValidateEmailAddressResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "ValidateEmailAddress", targetNamespace = "http://WebXml.com.cn/", className = "com.libf.ws.email.ValidateEmailAddress")
    @ResponseWrapper(localName = "ValidateEmailAddressResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.libf.ws.email.ValidateEmailAddressResponse")
    public short validateEmailAddress(
        @WebParam(name = "theEmail", targetNamespace = "http://WebXml.com.cn/")
        String theEmail);

    /**
     * <br /><h3>验证 Email 地址是否正确</h3><p>输入参数：EmailAddress = Email 地址，theEmailPort = SMTP端口（Integer），返回数据： Byte 字节。返回值同 ValidateEmailAddress</p><br />
     * 
     * @param theEmail
     * @param theEmailPort
     * @return
     *     returns short
     */
    @WebMethod(operationName = "ValidateEmailAddressPro", action = "http://WebXml.com.cn/ValidateEmailAddressPro")
    @WebResult(name = "ValidateEmailAddressProResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "ValidateEmailAddressPro", targetNamespace = "http://WebXml.com.cn/", className = "com.libf.ws.email.ValidateEmailAddressPro")
    @ResponseWrapper(localName = "ValidateEmailAddressProResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.libf.ws.email.ValidateEmailAddressProResponse")
    public short validateEmailAddressPro(
        @WebParam(name = "theEmail", targetNamespace = "http://WebXml.com.cn/")
        String theEmail,
        @WebParam(name = "theEmailPort", targetNamespace = "http://WebXml.com.cn/")
        int theEmailPort);

}
