
package com.libf.ws.email;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * <a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> <strong>Email地址验证 WEB 服务</strong>，通过查找给定的电子邮件域的邮件服务器和通过向邮件服务器发送数据来判断电子邮件地址正确与否。此Email地址验证Web Service请不要用于任何商业目的，若有需要请<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">联系我们</a>，欢迎技术交流。 QQ：8409035<br /><strong>使用本站 WEB 服务请注明或链接本站：http://www.webxml.com.cn/ 感谢大家的支持</strong>！<br /><br />&nbsp;
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ValidateEmailWebService", targetNamespace = "http://WebXml.com.cn/", wsdlLocation = "http://www.webxml.com.cn/WebServices/ValidateEmailWebService.asmx?wsdl")
public class ValidateEmailWebService
    extends Service
{

    private final static URL VALIDATEEMAILWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException VALIDATEEMAILWEBSERVICE_EXCEPTION;
    private final static QName VALIDATEEMAILWEBSERVICE_QNAME = new QName("http://WebXml.com.cn/", "ValidateEmailWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.webxml.com.cn/WebServices/ValidateEmailWebService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VALIDATEEMAILWEBSERVICE_WSDL_LOCATION = url;
        VALIDATEEMAILWEBSERVICE_EXCEPTION = e;
    }

    public ValidateEmailWebService() {
        super(__getWsdlLocation(), VALIDATEEMAILWEBSERVICE_QNAME);
    }

    public ValidateEmailWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALIDATEEMAILWEBSERVICE_QNAME, features);
    }

    public ValidateEmailWebService(URL wsdlLocation) {
        super(wsdlLocation, VALIDATEEMAILWEBSERVICE_QNAME);
    }

    public ValidateEmailWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALIDATEEMAILWEBSERVICE_QNAME, features);
    }

    public ValidateEmailWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidateEmailWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ValidateEmailWebServiceSoap
     */
    @WebEndpoint(name = "ValidateEmailWebServiceSoap")
    public ValidateEmailWebServiceSoap getValidateEmailWebServiceSoap() {
        return super.getPort(new QName("http://WebXml.com.cn/", "ValidateEmailWebServiceSoap"), ValidateEmailWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidateEmailWebServiceSoap
     */
    @WebEndpoint(name = "ValidateEmailWebServiceSoap")
    public ValidateEmailWebServiceSoap getValidateEmailWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "ValidateEmailWebServiceSoap"), ValidateEmailWebServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns ValidateEmailWebServiceSoap
     */
    @WebEndpoint(name = "ValidateEmailWebServiceSoap12")
    public ValidateEmailWebServiceSoap getValidateEmailWebServiceSoap12() {
        return super.getPort(new QName("http://WebXml.com.cn/", "ValidateEmailWebServiceSoap12"), ValidateEmailWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidateEmailWebServiceSoap
     */
    @WebEndpoint(name = "ValidateEmailWebServiceSoap12")
    public ValidateEmailWebServiceSoap getValidateEmailWebServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "ValidateEmailWebServiceSoap12"), ValidateEmailWebServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns ValidateEmailWebServiceHttpGet
     */
    @WebEndpoint(name = "ValidateEmailWebServiceHttpGet")
    public ValidateEmailWebServiceHttpGet getValidateEmailWebServiceHttpGet() {
        return super.getPort(new QName("http://WebXml.com.cn/", "ValidateEmailWebServiceHttpGet"), ValidateEmailWebServiceHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidateEmailWebServiceHttpGet
     */
    @WebEndpoint(name = "ValidateEmailWebServiceHttpGet")
    public ValidateEmailWebServiceHttpGet getValidateEmailWebServiceHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "ValidateEmailWebServiceHttpGet"), ValidateEmailWebServiceHttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns ValidateEmailWebServiceHttpPost
     */
    @WebEndpoint(name = "ValidateEmailWebServiceHttpPost")
    public ValidateEmailWebServiceHttpPost getValidateEmailWebServiceHttpPost() {
        return super.getPort(new QName("http://WebXml.com.cn/", "ValidateEmailWebServiceHttpPost"), ValidateEmailWebServiceHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidateEmailWebServiceHttpPost
     */
    @WebEndpoint(name = "ValidateEmailWebServiceHttpPost")
    public ValidateEmailWebServiceHttpPost getValidateEmailWebServiceHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "ValidateEmailWebServiceHttpPost"), ValidateEmailWebServiceHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDATEEMAILWEBSERVICE_EXCEPTION!= null) {
            throw VALIDATEEMAILWEBSERVICE_EXCEPTION;
        }
        return VALIDATEEMAILWEBSERVICE_WSDL_LOCATION;
    }

}
