
package com.libf.ws.email;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ValidateEmailWebServiceHttpPost", targetNamespace = "http://WebXml.com.cn/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ValidateEmailWebServiceHttpPost {


    /**
     * <br /><h3>验证 Email 地址是否正确</h3><p>输入参数：EmailAddress = Email 地址（默认SMTP端口25），返回数据： Byte 字节。返回值： 0 = 请重新验证；1 = 邮件地址合法；2 = 只是域名正确；3 = 一个未知错误；4 = 邮件服务器没有找到；5 = 电子邮件地址错误；6 = 免费用户验证超过数量（50次/24小时）；7 = 商业用户不能通过验证</p><br />
     * 
     * @param theEmail
     * @return
     *     returns short
     */
    @WebMethod(operationName = "ValidateEmailAddress")
    @WebResult(name = "unsignedByte", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    public short validateEmailAddress(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "theEmail")
        String theEmail);

    /**
     * <br /><h3>验证 Email 地址是否正确</h3><p>输入参数：EmailAddress = Email 地址，theEmailPort = SMTP端口（Integer），返回数据： Byte 字节。返回值同 ValidateEmailAddress</p><br />
     * 
     * @param theEmail
     * @param theEmailPort
     * @return
     *     returns short
     */
    @WebMethod(operationName = "ValidateEmailAddressPro")
    @WebResult(name = "unsignedByte", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    public short validateEmailAddressPro(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "theEmail")
        String theEmail,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "theEmailPort")
        String theEmailPort);

}
